### ISSUE TITLE
Default code doesn't pass validation

### ISSUE THREAD

**Issue by m-mohr** [stactools-packages/template#59] opened 2022-05-17 16:01 UTC
The default code doesn't seem to pass validation. After creating a repo and renaming stuff via the script, I get an error in test_commands.py.

It asks to change 
```py
            result = self.run_command(
                f"noaamrmsqpe create-item {infile} {destination}"
            )
```

to 
```py
            result = self.run_command(f"noaamrmsqpe create-item {infile} {destination}")
```

**Comment by pjhartzell** [comment] 2022-05-17 17:38
Is the name of your package `noaamrmsqpe`? If so, then
```
result = self.run_command(f"noaamrmsqpe create-item {infile} {destination}")
```
is correct. `ephemeralcmd` was correctly to `noaamrmsqpe`.

Regarding the format change, it _may_ be because after the rename, black wants to put everything on one line because it now fits ("noaamrmsqpe" one letter shorter than "ephemeralcmd").

**Comment by m-mohr** [comment] 2022-05-17 20:03
Yes it is, although it seems not ideal that the renaming script did remove the dashes/underscores. 

Ah, lol. Funny that this one character might be the case. So if it validates here without issues(?), I assume we can close here.

**Comment by pjhartzell** [comment] 2022-05-17 20:44
> it seems not ideal that the renaming script did remove the dashes/underscores.

Agreed. The renaming is not perfect. There is some manual editing to be done afterward.

I think it's OK to close this. I'm making a few minor changes to the template. I'll add a note in the README to run `pre-commit install` early in the process, which will take care of any formatting errors caused by the `rename` script before they get pushed and end up failing CI on GitHub.

**Closed** 2022-05-18 13:42 UTC
Labels: bug
